### ISSUE TITLE
4.1 can not startup after installing in the mac os of java 17 env

### ISSUE THREAD

**Issue by chensce** [ObeoNetwork/InformationSystem#108]
4.1 can not startup after installing in the mac os of java 17 env

**Comment by vrichard12** [comment]
Hi,
We're almost there, but not quite. This version of IS Designer has been homologated for Java 11 only.
The ISD 5.0 release that will be made in the first quarter of 2024 will be based on Eclipse 2023-03 and homologated for Java 17.
Can you give ISD 4.1 a try with Java 11?
Vincent

**Comment by vrichard12** [comment]
Hi,

If you have an intel processor then you need to use the `macosx.cocoa.x86_66` architecture bundle.
Also, as I mentioned before, this release will not work on Java 17. The next release will.
For this release you will need to install and use a x86 jdk.

You can get such a Jdk from here for instance: https://adoptium.net/fr/temurin/releases/?variant=openjdk11&os=mac&arch=x64

To use it you will need to edit the `is-designer.ini` and add the `-vm` option at the beginning of it like so:

```
-vm
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
```

(Make sure the given path is valid according to your installation).

Please keep me informed!

BR

**Comment by chensce** [comment]
I will try java 11 tonight.
thank you!
Maybe we would translate the wiki to english

**Comment by chensce** [comment]
<img width="417" alt="Screen Shot 2023-12-22 at 10 37 14" src="https://github.com/ObeoNetwork/InformationSystem/assets/93559562/a82fbd96-99b4-48eb-8842-c7a08191b334">
<img width="439" alt="Screen Shot 2023-12-22 at 10 37 44" src="https://github.com/ObeoNetwork/InformationSystem/assets/93559562/cb070d51-3558-4cb0-ba4b-a67d749edb36">
I installed the jdk11

**Comment by chensce** [comment]
xattr -cr /Applications/ISDesigner.app
after these command,I can open the app.

**Comment by chensce** [comment]
@vrichard12 thank you very much.

**Comment by vrichard12** [comment]
Glad I could help. Thanks to you too for your feedback!
