### ISSUE TITLE
Missing /model/soa.genmodel from soa plugin jar

### ISSUE THREAD

**Issue by bodabela** [ObeoNetwork/InformationSystem#95]
Hi,

I am missing the **.genmodel** from the plugin jar of soa model (e.g. org.obeonetwork.dsl.soa_3.1.0.202211251051.jar).
All the other referenced models (env & technicalId) have the .genmodel in the **/model** path next to the .ecore.

Is it on purpose that both .genmodel and .aird files are missing? Am I missing something here?

I would like to leverage/reference the soa meta model in other metamodels and I have to create a project as a workaround that actually holds the genmodel created based on .ecore. The problem with that it is not sustainable if the soa model gets changed in upcoming versions.

Thanks!

**Comment by vrichard12** [comment]
Hi,

The genmodel is not used at runtime, thus it doesn't have to be part of the final product.
If you need to have a look at it then it is available here on the github repository :
https://github.com/ObeoNetwork/InformationSystem/blob/master/models/soa/plugins/org.obeonetwork.dsl.soa/model/soa.genmodel

Best regards,

Vincent

**Comment by bodabela** [comment]
Thank you. Let me explain what I am doing briefly. I have added Ecore Tools to the IS Designer and I leverage/extend the soa metamodel in a custom metamodel. I am not using the IS Designer platform as primarily intended, its role is more like the Obeo Designer's in this case.

Anyway, it is very useful that the environment, the entity, the technical id and other genmodels are accessible as platform resources. The only one - the most important one actually - that is missing is the soa genmodel.

Is it possible to add it to the upcoming versions the same way as the other genmodels are?

Thanks!

**Comment by vrichard12** [comment]
Ok I see. I'm wondering why you don't use a clone of the repository instead of the deployed jar plugins.
Anyway, I guess I can do it in the concern of standardizing the practices. :)
