### ISSUE TITLE
Is InformationSystem released as a Free Software?

### ISSUE THREAD

**Issue by bzg** [ObeoNetwork/InformationSystem#98]
Sorry if I'm missing something but I cannot find a license in this repository.

https://www.wikidata.org/wiki/Q112578937 seems to indicate that the license is the EPL. 

Is it true? If so, can you mention this in a proper LICENSE file?

**Comment by vrichard12** [comment]
However, this makes me realize that we still use EPL v1 which is now obsolete.
I'm going to update it to EPL v2.

**Comment by vrichard12** [comment]
Hello Bastien,

I have just done the following changes in the repository:
- Update all files headers to mention "Eclipse Public License v2.0" and "https://www.eclipse.org/legal/epl-2.0/" (3813 impacted files)
- Update README to mention EPL license
- Update releng/org.obeonetwork.is.license license feature to include EPL v2.0
- Create a LICENSE file at the root of the repository to make it more visible.

Please tell me if you still see something odd or if we can close the issue.

Thank you for your feedback!

Vincent

**Comment by bzg** [comment]
Hello Vincent, LGTM, thanks for the swift fix!
